pipeline {
    agent any
    environment {
      DEV_IP = sh(script: 'cat /usr/share/app_dev_ip.txt', , returnStdout: true).trim()
           }
    
    stages {
    
    
        stage('Build') {
            options {
                timeout(time: 11, unit: "MINUTES")
            }
            steps {
             catchError(buildResult: 'SUCCESS', stageResult: 'ABORTED') {
              withCredentials([sshUserPrivateKey(credentialsId: 'SSH_ubuntu', keyFileVariable: 'keyfile', usernameVariable: 'userName')]) {
                script {
                  def remote = [:]
                  remote.name = 'node'
                  remote.host = "$DEV_IP"
                  remote.allowAnyHosts = true
                  remote.user = userName
                  remote.identityFile = keyFile
                  sshCommand remote: remote, command: 'echo Version is ${BUILD_DATE_FORMATTED, "yy.MM.dd"}'
                  sshCommand remote: remote, command: '/opt/tomcat/apache-tomcat-8.5.57/bin/shutdown.sh'
                  sshCommand remote: remote, command: '[ -d "/home/ubuntu/.m2" ] &&   sudo rm -r /home/ubuntu/intermine  || echo "directory .m2 does not exist yet" ' 
                  sshCommand remote: remote, command: '[ -d "/home/ubuntu/.intermine" ] &&   sudo rm -r /home/ubuntu/intermine  || echo "directory .intermine does not exist yet" '
                  sshCommand remote: remote, command: '[ -d "/home/ubuntu/.gradle" ] &&   sudo rm -r /home/ubuntu/intermine  || echo "directory .gradle does not exist yet" '
                  sshCommand remote: remote, command: '[ -d "/home/ubuntu/intermine" ] &&   sudo rm -r /home/ubuntu/intermine  || echo "directory intermine does not exist yet" ' 
                  sshCommand remote: remote, command: '[ -n  $("lsof -i :8080 | grep java") ] && killall java || echo "Java not running yet"'
                  sshCommand remote: remote, command: "sudo git clone --branch master https://github.com/MariiaMarkina/intermine_final /home/ubuntu/intermine"
                  sshCommand remote: remote, command: 'export GRADLE_USER_HOME="/home/ubuntu"'
                  ${BUILD_DATE_FORMATTED, "yyyy-MM-dd"} 
                  sshCommand remote: remote, command: '/home/ubuntu/intermine/testmine/setup.sh'
                  //sshCommand remote: remote, command: 'lsof -i :8080 | grep "java" | awk "{print $2}" | xargs kill'
                 }
              }
             }
            }
        }
        
        
        
        stage('Deploy to local tomcat') {
            steps {
              withCredentials([sshUserPrivateKey(credentialsId: 'SSH_ubuntu', keyFileVariable: 'keyfile', usernameVariable: 'userName')]) {
                script {
                  def remote = [:]
                  remote.name = 'node'
                  remote.host = "$DEV_IP"
                  remote.allowAnyHosts = true
                  remote.user = userName
                  remote.identityFile = keyFile
                  sshCommand remote: remote, command: 'killall java'
                  sshCommand remote: remote, command: 'cp -R /home/ubuntu/intermine/testmine/webapp/build/serverBaseDir_tomcat8/work/Tomcat/localhost/intermine-demo /opt/tomcat/apache-tomcat-8.5.57/webapps/'
                  sshCommand remote: remote, command: 'cp -R /home/ubuntu/intermine/testmine/webapp/build/serverBaseDir_tomcat8/webapps/intermine-demo /opt/tomcat/apache-tomcat-8.5.57/webapps/'
                  sshCommand remote: remote, command: 'sudo /opt/tomcat/apache-tomcat-8.5.57/bin/startup.sh'
                  //sshCommand remote: remote, command: 'cp -R /opt/tomcat/apache-tomcat-8.5.57/webapps/intermine-demo /home/ubuntu/webapps/intermine-demo'
                  //sshCommand remote: remote, command: 'tar -cvf /home/ubuntu/myarchive.tar /home/ubuntu/webapps/intermine-demo'
                 // sshGet remote: remote, from: '/home/ubuntu/myarchive.tar', into: './myarchive.tar', override: true
                }
              }
             
            }
        }
        
        
        stage('Test') {
            steps {
                sh 'sleep 20'
                sh 'wget -S "$DEV_IP:8070/intermine-demo"'
              }
        }
        
        
        stage('Write version to /home/ubuntu/appversion.txt on instance') {
            steps {
              withCredentials([sshUserPrivateKey(credentialsId: 'SSH_ubuntu', keyFileVariable: 'keyfile', usernameVariable: 'userName')]) {
                script {
                  def remote = [:]
                  remote.name = 'node'
                  remote.host = "$DEV_IP"
                  remote.allowAnyHosts = true
                  remote.user = userName
                  remote.identityFile = keyFile
                  sshCommand remote: remote, command: '[ -f "/home/ubuntu/appversion.txt" ] &&   echo "file for versions already exists" || touch /home/ubuntu/appversion.txt" '
                  sshCommand remote: remote, command: 'echo ${BUILD_DATE_FORMATTED, "yy.MM.dd"} > /home/ubuntu/appversion.txt'
                  sshCommand remote: remote, command: 'cp -R /home/ubuntu/intermine/testmine/webapp/build/serverBaseDir_tomcat8/webapps/intermine-demo /opt/tomcat/apache-tomcat-8.5.57/webapps/'
                  sshCommand remote: remote, command: 'sudo /opt/tomcat/apache-tomcat-8.5.57/bin/startup.sh'
                  
                }
              }
             
            }
        }
        
        
        //stage('Deploy to prod') {
          //  steps {
             // withCredentials([sshUserPrivateKey(credentialsId: 'SSH_ubuntu', keyFileVariable: 'keyfile', usernameVariable: 'userName')]) {
             //   script {
              //    def remote = [:]
               //   remote.name = 'node'
               //   remote.host = 'ec2-52-207-239-235.compute-1.amazonaws.com'
                //  remote.allowAnyHosts = true
                //  remote.user = userName
                //  remote.identityFile = keyFile

              //    sshPut remote: remote, from: './myarchive.tar', into: '/home/ubuntu/myarchive.tar'
               //   sshCommand remote: remote, command: 'tar -xf /home/ubuntu/myarchive.tar'  
               //   sshCommand remote: remote, command: 'cp -R /home/ubuntu/home/ubuntu/webapps/intermine-demo /opt/tomcat/apache-tomcat-8.5.57/webapps/intermine-demo/'
                  
               // }
             // }
             
            //}
      //  }
        
        
       
        
        
    }
}
